package xin.liujiajun.mq.rocketmq.producer;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GatewayMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GatewayMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>string mac = 2;</code>
     */
    String getMac();
    /**
     * <code>string mac = 2;</code>
     */
    com.google.protobuf.ByteString
        getMacBytes();

    /**
     * <code>string sessionId = 3;</code>
     */
    String getSessionId();
    /**
     * <code>string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>int32 dataType = 5;</code>
     */
    int getDataType();

    /**
     * <code>bool finFlag = 6;</code>
     */
    boolean getFinFlag();
  }
  /**
   * Protobuf type {@code GatewayMsg}
   */
  public  static final class GatewayMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GatewayMsg)
      GatewayMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GatewayMsg.newBuilder() to construct.
    private GatewayMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GatewayMsg() {
      type_ = 0;
      mac_ = "";
      sessionId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      dataType_ = 0;
      finFlag_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GatewayMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              mac_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
            case 40: {

              dataType_ = input.readInt32();
              break;
            }
            case 48: {

              finFlag_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_GatewayMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_GatewayMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GatewayMsg.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int MAC_FIELD_NUMBER = 2;
    private volatile Object mac_;
    /**
     * <code>string mac = 2;</code>
     */
    public String getMac() {
      Object ref = mac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      }
    }
    /**
     * <code>string mac = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private volatile Object sessionId_;
    /**
     * <code>string sessionId = 3;</code>
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 4;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int DATATYPE_FIELD_NUMBER = 5;
    private int dataType_;
    /**
     * <code>int32 dataType = 5;</code>
     */
    public int getDataType() {
      return dataType_;
    }

    public static final int FINFLAG_FIELD_NUMBER = 6;
    private boolean finFlag_;
    /**
     * <code>bool finFlag = 6;</code>
     */
    public boolean getFinFlag() {
      return finFlag_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mac_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      if (dataType_ != 0) {
        output.writeInt32(5, dataType_);
      }
      if (finFlag_ != false) {
        output.writeBool(6, finFlag_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mac_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      if (dataType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, dataType_);
      }
      if (finFlag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, finFlag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GatewayMsg)) {
        return super.equals(obj);
      }
      GatewayMsg other = (GatewayMsg) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getMac()
          .equals(other.getMac());
      result = result && getSessionId()
          .equals(other.getSessionId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getDataType()
          == other.getDataType());
      result = result && (getFinFlag()
          == other.getFinFlag());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType();
      hash = (37 * hash) + FINFLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFinFlag());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GatewayMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GatewayMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GatewayMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GatewayMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GatewayMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GatewayMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GatewayMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GatewayMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GatewayMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GatewayMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GatewayMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GatewayMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GatewayMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GatewayMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GatewayMsg)
        GatewayMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_GatewayMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_GatewayMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GatewayMsg.class, Builder.class);
      }

      // Construct using Message.GatewayMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        mac_ = "";

        sessionId_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        dataType_ = 0;

        finFlag_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_GatewayMsg_descriptor;
      }

      public GatewayMsg getDefaultInstanceForType() {
        return GatewayMsg.getDefaultInstance();
      }

      public GatewayMsg build() {
        GatewayMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GatewayMsg buildPartial() {
        GatewayMsg result = new GatewayMsg(this);
        result.type_ = type_;
        result.mac_ = mac_;
        result.sessionId_ = sessionId_;
        result.content_ = content_;
        result.dataType_ = dataType_;
        result.finFlag_ = finFlag_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GatewayMsg) {
          return mergeFrom((GatewayMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GatewayMsg other) {
        if (other == GatewayMsg.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getMac().isEmpty()) {
          mac_ = other.mac_;
          onChanged();
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.getDataType() != 0) {
          setDataType(other.getDataType());
        }
        if (other.getFinFlag() != false) {
          setFinFlag(other.getFinFlag());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GatewayMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GatewayMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object mac_ = "";
      /**
       * <code>string mac = 2;</code>
       */
      public String getMac() {
        Object ref = mac_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mac = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        Object ref = mac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mac = 2;</code>
       */
      public Builder setMac(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 2;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 2;</code>
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mac_ = value;
        onChanged();
        return this;
      }

      private Object sessionId_ = "";
      /**
       * <code>string sessionId = 3;</code>
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public Builder setSessionId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 4;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private int dataType_ ;
      /**
       * <code>int32 dataType = 5;</code>
       */
      public int getDataType() {
        return dataType_;
      }
      /**
       * <code>int32 dataType = 5;</code>
       */
      public Builder setDataType(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataType = 5;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private boolean finFlag_ ;
      /**
       * <code>bool finFlag = 6;</code>
       */
      public boolean getFinFlag() {
        return finFlag_;
      }
      /**
       * <code>bool finFlag = 6;</code>
       */
      public Builder setFinFlag(boolean value) {
        
        finFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool finFlag = 6;</code>
       */
      public Builder clearFinFlag() {
        
        finFlag_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GatewayMsg)
    }

    // @@protoc_insertion_point(class_scope:GatewayMsg)
    private static final GatewayMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GatewayMsg();
    }

    public static GatewayMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GatewayMsg>
        PARSER = new com.google.protobuf.AbstractParser<GatewayMsg>() {
      public GatewayMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GatewayMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GatewayMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GatewayMsg> getParserForType() {
      return PARSER;
    }

    public GatewayMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MqMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MqMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>string sessionId = 2;</code>
     */
    String getSessionId();
    /**
     * <code>string sessionId = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>string mac = 3;</code>
     */
    String getMac();
    /**
     * <code>string mac = 3;</code>
     */
    com.google.protobuf.ByteString
        getMacBytes();

    /**
     * <code>bool finFlag = 4;</code>
     */
    boolean getFinFlag();

    /**
     * <code>int32 dataType = 5;</code>
     */
    int getDataType();

    /**
     * <code>int32 responseResult = 6;</code>
     */
    int getResponseResult();

    /**
     * <code>bytes content = 7;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>string host = 8;</code>
     */
    String getHost();
    /**
     * <code>string host = 8;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 9;</code>
     */
    int getPort();

    /**
     * <code>string channelId = 10;</code>
     */
    String getChannelId();
    /**
     * <code>string channelId = 10;</code>
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>string version = 11;</code>
     */
    String getVersion();
    /**
     * <code>string version = 11;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string fileName = 12;</code>
     */
    String getFileName();
    /**
     * <code>string fileName = 12;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string fileType = 13;</code>
     */
    String getFileType();
    /**
     * <code>string fileType = 13;</code>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();
  }
  /**
   * Protobuf type {@code MqMsg}
   */
  public  static final class MqMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MqMsg)
      MqMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MqMsg.newBuilder() to construct.
    private MqMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MqMsg() {
      type_ = 0;
      sessionId_ = "";
      mac_ = "";
      finFlag_ = false;
      dataType_ = 0;
      responseResult_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      host_ = "";
      port_ = 0;
      channelId_ = "";
      version_ = "";
      fileName_ = "";
      fileType_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              mac_ = s;
              break;
            }
            case 32: {

              finFlag_ = input.readBool();
              break;
            }
            case 40: {

              dataType_ = input.readInt32();
              break;
            }
            case 48: {

              responseResult_ = input.readInt32();
              break;
            }
            case 58: {

              content_ = input.readBytes();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 72: {

              port_ = input.readInt32();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              fileType_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_MqMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_MqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MqMsg.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private volatile Object sessionId_;
    /**
     * <code>string sessionId = 2;</code>
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAC_FIELD_NUMBER = 3;
    private volatile Object mac_;
    /**
     * <code>string mac = 3;</code>
     */
    public String getMac() {
      Object ref = mac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      }
    }
    /**
     * <code>string mac = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINFLAG_FIELD_NUMBER = 4;
    private boolean finFlag_;
    /**
     * <code>bool finFlag = 4;</code>
     */
    public boolean getFinFlag() {
      return finFlag_;
    }

    public static final int DATATYPE_FIELD_NUMBER = 5;
    private int dataType_;
    /**
     * <code>int32 dataType = 5;</code>
     */
    public int getDataType() {
      return dataType_;
    }

    public static final int RESPONSERESULT_FIELD_NUMBER = 6;
    private int responseResult_;
    /**
     * <code>int32 responseResult = 6;</code>
     */
    public int getResponseResult() {
      return responseResult_;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 7;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int HOST_FIELD_NUMBER = 8;
    private volatile Object host_;
    /**
     * <code>string host = 8;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 8;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 9;
    private int port_;
    /**
     * <code>int32 port = 9;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 10;
    private volatile Object channelId_;
    /**
     * <code>string channelId = 10;</code>
     */
    public String getChannelId() {
      Object ref = channelId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>string channelId = 10;</code>
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 11;
    private volatile Object version_;
    /**
     * <code>string version = 11;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 11;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAME_FIELD_NUMBER = 12;
    private volatile Object fileName_;
    /**
     * <code>string fileName = 12;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILETYPE_FIELD_NUMBER = 13;
    private volatile Object fileType_;
    /**
     * <code>string fileType = 13;</code>
     */
    public String getFileType() {
      Object ref = fileType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      }
    }
    /**
     * <code>string fileType = 13;</code>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
      }
      if (!getMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mac_);
      }
      if (finFlag_ != false) {
        output.writeBool(4, finFlag_);
      }
      if (dataType_ != 0) {
        output.writeInt32(5, dataType_);
      }
      if (responseResult_ != 0) {
        output.writeInt32(6, responseResult_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(7, content_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, host_);
      }
      if (port_ != 0) {
        output.writeInt32(9, port_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, channelId_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, version_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, fileName_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, fileType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
      }
      if (!getMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mac_);
      }
      if (finFlag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, finFlag_);
      }
      if (dataType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, dataType_);
      }
      if (responseResult_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, responseResult_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, content_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, port_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, channelId_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, version_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, fileName_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, fileType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MqMsg)) {
        return super.equals(obj);
      }
      MqMsg other = (MqMsg) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getSessionId()
          .equals(other.getSessionId());
      result = result && getMac()
          .equals(other.getMac());
      result = result && (getFinFlag()
          == other.getFinFlag());
      result = result && (getDataType()
          == other.getDataType());
      result = result && (getResponseResult()
          == other.getResponseResult());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && getChannelId()
          .equals(other.getChannelId());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && getFileType()
          .equals(other.getFileType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (37 * hash) + FINFLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFinFlag());
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType();
      hash = (37 * hash) + RESPONSERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResponseResult();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MqMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MqMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MqMsg)
        MqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_MqMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_MqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MqMsg.class, Builder.class);
      }

      // Construct using Message.MqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        sessionId_ = "";

        mac_ = "";

        finFlag_ = false;

        dataType_ = 0;

        responseResult_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        host_ = "";

        port_ = 0;

        channelId_ = "";

        version_ = "";

        fileName_ = "";

        fileType_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_MqMsg_descriptor;
      }

      public MqMsg getDefaultInstanceForType() {
        return MqMsg.getDefaultInstance();
      }

      public MqMsg build() {
        MqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MqMsg buildPartial() {
        MqMsg result = new MqMsg(this);
        result.type_ = type_;
        result.sessionId_ = sessionId_;
        result.mac_ = mac_;
        result.finFlag_ = finFlag_;
        result.dataType_ = dataType_;
        result.responseResult_ = responseResult_;
        result.content_ = content_;
        result.host_ = host_;
        result.port_ = port_;
        result.channelId_ = channelId_;
        result.version_ = version_;
        result.fileName_ = fileName_;
        result.fileType_ = fileType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MqMsg) {
          return mergeFrom((MqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MqMsg other) {
        if (other == MqMsg.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (!other.getMac().isEmpty()) {
          mac_ = other.mac_;
          onChanged();
        }
        if (other.getFinFlag() != false) {
          setFinFlag(other.getFinFlag());
        }
        if (other.getDataType() != 0) {
          setDataType(other.getDataType());
        }
        if (other.getResponseResult() != 0) {
          setResponseResult(other.getResponseResult());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getFileType().isEmpty()) {
          fileType_ = other.fileType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MqMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object sessionId_ = "";
      /**
       * <code>string sessionId = 2;</code>
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sessionId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionId = 2;</code>
       */
      public Builder setSessionId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 2;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 2;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private Object mac_ = "";
      /**
       * <code>string mac = 3;</code>
       */
      public String getMac() {
        Object ref = mac_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mac = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        Object ref = mac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mac = 3;</code>
       */
      public Builder setMac(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 3;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 3;</code>
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mac_ = value;
        onChanged();
        return this;
      }

      private boolean finFlag_ ;
      /**
       * <code>bool finFlag = 4;</code>
       */
      public boolean getFinFlag() {
        return finFlag_;
      }
      /**
       * <code>bool finFlag = 4;</code>
       */
      public Builder setFinFlag(boolean value) {
        
        finFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool finFlag = 4;</code>
       */
      public Builder clearFinFlag() {
        
        finFlag_ = false;
        onChanged();
        return this;
      }

      private int dataType_ ;
      /**
       * <code>int32 dataType = 5;</code>
       */
      public int getDataType() {
        return dataType_;
      }
      /**
       * <code>int32 dataType = 5;</code>
       */
      public Builder setDataType(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataType = 5;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private int responseResult_ ;
      /**
       * <code>int32 responseResult = 6;</code>
       */
      public int getResponseResult() {
        return responseResult_;
      }
      /**
       * <code>int32 responseResult = 6;</code>
       */
      public Builder setResponseResult(int value) {
        
        responseResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseResult = 6;</code>
       */
      public Builder clearResponseResult() {
        
        responseResult_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 7;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 7;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 7;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private Object host_ = "";
      /**
       * <code>string host = 8;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string host = 8;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 8;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 8;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 8;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 9;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 9;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 9;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private Object channelId_ = "";
      /**
       * <code>string channelId = 10;</code>
       */
      public String getChannelId() {
        Object ref = channelId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string channelId = 10;</code>
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channelId = 10;</code>
       */
      public Builder setChannelId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 10;</code>
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 10;</code>
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>string version = 11;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string version = 11;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 11;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 11;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 11;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private Object fileName_ = "";
      /**
       * <code>string fileName = 12;</code>
       */
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fileName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 12;</code>
       */
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 12;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 12;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private Object fileType_ = "";
      /**
       * <code>string fileType = 13;</code>
       */
      public String getFileType() {
        Object ref = fileType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fileType = 13;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileType = 13;</code>
       */
      public Builder setFileType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 13;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 13;</code>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MqMsg)
    }

    // @@protoc_insertion_point(class_scope:MqMsg)
    private static final MqMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MqMsg();
    }

    public static MqMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MqMsg>
        PARSER = new com.google.protobuf.AbstractParser<MqMsg>() {
      public MqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MqMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MqMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MqMsg> getParserForType() {
      return PARSER;
    }

    public MqMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GatewayMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GatewayMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MqMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MqMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\"n\n\nGatewayMsg\022\014\n\004type\030\001 " +
      "\001(\005\022\013\n\003mac\030\002 \001(\t\022\021\n\tsessionId\030\003 \001(\t\022\017\n\007c" +
      "ontent\030\004 \001(\014\022\020\n\010dataType\030\005 \001(\005\022\017\n\007finFla" +
      "g\030\006 \001(\010\"\345\001\n\005MqMsg\022\014\n\004type\030\001 \001(\005\022\021\n\tsessi" +
      "onId\030\002 \001(\t\022\013\n\003mac\030\003 \001(\t\022\017\n\007finFlag\030\004 \001(\010" +
      "\022\020\n\010dataType\030\005 \001(\005\022\026\n\016responseResult\030\006 \001" +
      "(\005\022\017\n\007content\030\007 \001(\014\022\014\n\004host\030\010 \001(\t\022\014\n\004por" +
      "t\030\t \001(\005\022\021\n\tchannelId\030\n \001(\t\022\017\n\007version\030\013 " +
      "\001(\t\022\020\n\010fileName\030\014 \001(\t\022\020\n\010fileType\030\r \001(\tb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GatewayMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GatewayMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GatewayMsg_descriptor,
        new String[] { "Type", "Mac", "SessionId", "Content", "DataType", "FinFlag", });
    internal_static_MqMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MqMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MqMsg_descriptor,
        new String[] { "Type", "SessionId", "Mac", "FinFlag", "DataType", "ResponseResult", "Content", "Host", "Port", "ChannelId", "Version", "FileName", "FileType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
